export const API = {
  Web: {
    Heartbeat: '/heartbeat',
  },
  Auth: {
    History: '/api/auth/history',
    Current: '/api/auth/current',
    Login: '/api/auth/login',
    Logout: '/api/auth/logout',
    Check: '/api/auth/check',
  },
  Alarm: {
    All: '/api/alarm/all',
    Top: '/api/alarm/top',
    Info: '/api/alarm/info',
    Delete: '/api/alarm/del',
  },
  App: {
    All: '/api/app/all',
    Count: '/api/app/count',
    Info: '/api/app/info',
    Status: '/api/app/status',
    Tree: '/api/app/tree',
    Proc: '/api/app/proc',
    Ports: '/api/app/ports',
    Start: '/api/app/start',
    StartAll: '/api/app/startall',
    Stop: '/api/app/stop',
    StopAll: '/api/app/stopall',
    Restart: '/api/app/restart',
    Upload: '/api/app/upload',
    Remove: '/api/app/remove',
    Backup: '/api/app/backup',
  },
  Container: {
    Container: '/api/container/containers',
    Image: '/api/container/images',
    Start: '/api/container/start',
    Stop: '/api/container/stop',
    Remove: '/api/container/remove',
  },
  Database: {
    List: '/api/database/list',
    Info: '/api/database',
  },
  Env: {
    List: '/api/env/list',
    Show: '/api/env/show',
    Get: '/api/env/get',
    Decrypt: '/api/env/decrypt',
    Set: '/api/env/set',
    Delete: '/api/env/delete',
  },
  Indicator: {
    Sys: '/api/indicator/sys',
    Memory: '/api/indicator/mem',
    Load: '/api/indicator/load',
    Cpu: '/api/indicator/cpu',
    IO: '/api/indicator/io',
    Network: '/api/indicator/network',
  },
  Log: {
    List: '/api/log/list',
    Info: '/api/log',
    Download: '/api/log/download',
    Clear: '/api/log/clear',
  },
  Modules: {
    All: '/api/modules/all',
    Info: '/api/modules',
  },
  NoEngine: {
    Get: '/api/noengine',
    All: '/api/noengine/all',
    Status: '/api/noengine/status',
    Start: '/api/noengine/start',
    Stop: '/api/noengine/stop',
    Restart: '/api/noengine/restart',
    Resume: '/api/noengine/resume',
    Pause: '/api/noengine/pause',
    Remove: '/api/noengine/remove',
    Refresh: '/api/noengine/refresh',
  },
  NoEngineX: {
    Status: '/api/noengine/x/status',
    Start: '/api/noengine/x/start',
    Stop: '/api/noengine/x/stop',
    Restart: '/api/noengine/x/restart',
    Resume: '/api/noengine/x/resume',
    Pause: '/api/noengine/x/pause',
    Remove: '/api/noengine/x/remove',
    Refresh: '/api/noengine/x/refresh',
  },
  OAuth: {
    Github: '/api/oauth/github',
    Check: '/api/oauth/check',
    Login: '/api/oauth/login',
    Logout: '/api/oauth/logout',
    Sync: '/api/oauth/sync',
  },
  Repo: {
    List: '/api/repo/list',
    Get: '/api/repo',
    Commits: '/api/repo/commits',
    SyncRepo: '/api/repo/sync/repos',
    SyncCommits: '/api/repo/sync/commits',
  },
  Script: {
    List: '/api/script/list',
    TaskList: '/api/script/task/list',
    Task: '/api/script/task',
    Start: '/api/script/task/start',
    Stop: '/api/script/task/stop',
    Delete: '/api/script/task/delete',
  },
  Status: {
    Status: '/api/status',
  },
  System: {
    Overview: '/api/system/overview',
    Pid: '/api/system/pid',
    Config: '/api/system/config',
    Info: '/api/system/info',
    Save: '/api/system/save',
    Reload: '/api/system/reload',
    Clear: '/api/system/clear',
    Cert: '/api/system/cert',
  },
  Task: {
    Background: '/api/task/bg',
    Cron: '/api/task/cron',
  },
  // 扩展外部API接口
  Panel: {
    APIStat: '/api/panel/network/stat',
    APIGeo: '/api/panel/network/geo',
    APIDomain: '/api/panel/network/domain',
    APIProcessList: '/api/panel/process/list',
    APIProcess: '/api/panel/process',
  }
}