export const Route = {
  Origin: {
    Index: '/',
    Home: '/home',
    Panel: '/panel',
    PanelAdvance: '/panel/advance',
    PanelDashboard: '/panel/dashboard',
    PanelModule: '/panel/api/module',
  },
  Next: {
    Index: '/next',
    Home: '/next/start',
    Login: '/next/login',
    App: '/next/app',
    AppSelect: '/next/select',
    AppTree: '/next/tree',
    Container: '/next/container',
    Task: '/next/task',
    Alarm: '/next/alarm',
    Log: '/next/log',
    Repo: '/next/repo',
    DB: '/next/db',
    System: '/next/system',
    Indicator: '/next/indicator',
    Cert: '/next/cert',
    Env: '/next/env',
    Terminal: '/next/terminal',
    Gateway: '/next/gw',
    NoEngine: '/next/noengine',
    Script: '/next/script',
    ScriptTask: '/next/script/task',
    PanelNetwork: '/next/panel/network',
    PanelApp: '/next/panel/app',
    PanelSecure: '/next/panel/secure',
    Setting: '/next/setting',
    CLI: '/next/cli',
    ChangeLog: '/next/changelog',
    About: '/next/about',
  },
};